version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./resources:/app/resources  # Monta o diretório resources do host no container
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
